services:
  itest:
    image: golang:1.22
    working_dir: /app
    tmpfs:
      - /external
      - /external_alt
    environment:
      - GOCOVERDIR=./coverage
    volumes:
      - ./gtrash:/app/gtrash:ro
      - ./itest:/app/itest
      - ./go.mod:/app/go.mod:ro
    # privileged: true
    command:
      - /bin/bash
      - -c
      - |
        set -eu
        bash ./itest/setup.sh
        go test -v ./itest
